import React, { useState } from 'react';
import {
    Activity, CheckCircle, Search, Sparkles, Wallet, Zap
} from 'lucide-react';
import type { Project, User, Task, Asset, Client } from '../../../types/models';
import { TaskStatus } from '../../../types/models';
import type { PredictiveInsight } from '../../../types/analytics';
import { api } from '../../../services/api';
// import { GemPhotoAI } from '../GemPhotoAI';
// import { ProjectQuickView } from '../ProjectQuickView';
// import { NotificationBell } from '../NotificationBell';
import { GlassMetric } from '../ui/GlassMetric';
import { useDashboardAnalytics } from '../../../hooks/useDashboardAnalytics';
import type { DashboardFilter } from '../../../types/analytics';

import { RiskMatrix } from './RiskMatrix';
import { OracleWidget } from './OracleWidget';
import { TeamVelocity } from './TeamVelocity';
import { RevenueBreakdown } from './RevenueBreakdown';
import { ClientPipeline } from './ClientPipeline';
import { BudgetTrend } from './BudgetTrend';

interface AdminDashboardProps {
    user: User;
    projects: Project[];
    tasks: Task[];
    assets: Asset[];
    users: User[];
    clients: Client[];
}

export const AdminDashboard: React.FC<AdminDashboardProps> = ({ user, projects, tasks, assets, users, clients }) => {
    // const [showGemAI, setShowGemAI] = useState(false);
    // const [filters, setFilters] = useState<DashboardFilter>({});
    const filters: DashboardFilter = {}; // Default empty filters
    const [zoomedTile, setZoomedTile] = useState<string | null>(null);
    const [nlQuery, setNlQuery] = useState('');
    const [insight, setInsight] = useState<PredictiveInsight | null>(null);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    // const [selectedProject, setSelectedProject] = useState<Project | null>(null);

    // --- ANALYTICS HOOK ---
    const analytics = useDashboardAnalytics(projects, tasks, assets, users, clients, filters, nlQuery);

    // --- INITIALIZATION ---
    React.useEffect(() => {
        runPrediction();
    }, []);

    // --- AI PREDICTION HANDLER (BACKEND) ---
    const runPrediction = async () => {
        setIsAnalyzing(true);
        const scenario = {
            projects: projects.map(p => ({
                name: p.name,
                budget: p.budget,
                spent: p.spent || 0,
                progress: 0
            })),
            tasksCount: tasks.length,
            activeLoad: analytics.activeLoad,
            teamEfficiency: analytics.teamStats.map(t => ({ name: t.name, efficiency: t.efficiency }))
        };

        try {
            // Using existing oracleService via api instance or oracleService if imported
            // For now assuming we need a dedicated endpoint or reuse oracleService
            // Here using the new Oracle structure logic we implemented
            const result = await api.post('/oracle/simulate', scenario);
            // Result adapted to PredictiveInsight
            const data = result.data;

            setInsight({
                riskLevel: (data.riskLevel as 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL') || 'MEDIUM',
                prediction: data.prediction || 'Analysis complete based on current project velocity.',
                recommendation: data.recommendation || 'Monitor budget burn rates closely.',
                impactedProjects: []
            });
        } catch (e) {
            console.error("Prediction failed", e);
            setInsight({
                riskLevel: 'MEDIUM',
                prediction: 'Could not connect to Iris Oracle Engine.',
                recommendation: 'Check backend connection.',
                impactedProjects: []
            });
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handleChartClick = (data: any) => {
        if (data && data.payload && data.payload.payload) {
            // setSelectedProject(data.payload.payload as Project);
            console.log("Selected project:", data.payload.payload);
        }
    };

    /*
    const handleQuickAction = (action: string, projectId: string) => {

        if (action === 'add_budget') {
            alert(`Budget increase request sent for project ${projectId}`);
        }
        setSelectedProject(null);
    };
    */

    const handleExecuteRecommendation = async () => {
        if (!insight) return;
        if (!confirm('Create a high-priority task based on this recommendation?')) return;

        if (projects.length === 0) {
            alert("No active projects found. Please create a project first.");
            return;
        }

        try {
            await api.post('/tasks', {
                title: `Oracle Action: ${insight.recommendation}`,
                description: `Automatically generated by Oracle Insight.\nPrediction: ${insight.prediction}\nRisk Level: ${insight.riskLevel}`,
                status: TaskStatus.TODO,
                priority: 'HIGH',
                assigneeId: user.id,
                projectId: projects[0].id,
                dueDate: new Date(Date.now() + 86400000).toISOString()
            });
            alert('Task created successfully!');
        } catch (e) {
            console.error(e);
            alert('Failed to create task');
        }
    };


    return (
        <div className={`min-h-screen bg-slate-50/50 p-6 space-y-8 animate-in fade-in duration-700 ${zoomedTile ? 'overflow-hidden' : ''}`}>

            {/* HEADER & CONTROLS */}
            <div className="flex flex-col md:flex-row justify-between items-end md:items-center gap-6 relative z-10">
                <div>
                    <h1 className="text-4xl font-[Outfit] font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-3">
                        <div className="w-4 h-4 rounded-full bg-brand-500 animate-pulse shadow-[0_0_15px_rgba(163,255,0,0.5)]" />
                        Command Center
                    </h1>
                    <p className="text-slate-500 dark:text-brand-200 font-medium mt-1">Real-Time Agency Intelligence • {new Date().toLocaleDateString()}</p>
                </div>

                <div className="flex items-center gap-4 w-full md:w-auto">
                    <div className="relative group flex-1 md:w-80">
                        {/* Search Input */}
                        <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                            <Search className="h-5 w-5 text-slate-400 dark:text-brand-300 group-focus-within:text-brand-500 transition-colors" />
                        </div>
                        <input
                            type="text"
                            className="block w-full pl-11 pr-4 py-3 bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 shadow-lg dark:shadow-brand-900/50 rounded-2xl text-slate-700 dark:text-white placeholder-slate-400 dark:placeholder-white/30 focus:outline-none focus:ring-2 focus:ring-brand-500/50 transition-all backdrop-blur-md"
                            placeholder="Consult Iris Oracle or filter..."
                            value={nlQuery}
                            onChange={(e) => setNlQuery(e.target.value)}
                        />
                    </div>
                    {/* NOTIFICATION BELL */}
                    <div className="hidden md:block">
                        {/* <NotificationBell /> */}
                    </div>

                    <button
                        // onClick={() => setShowGemAI(true)}
                        className="px-6 py-3 bg-brand-600 hover:bg-brand-500 text-white rounded-2xl shadow-xl hover:shadow-brand-500/20 transition-all font-bold flex items-center gap-2 transform hover:-translate-y-0.5 border border-white/10 opacity-50 cursor-not-allowed"
                        title="Coming Soon"
                    >
                        <Sparkles size={18} className="text-accent" /> Gem Photo AI
                    </button>
                </div>
            </div>

            {/* KPI ROW */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <GlassMetric
                    title="Revenue Flow"
                    value={`$${analytics.totalBudget.toLocaleString()}`}
                    subtext="Active Pipeline"
                    icon={<Wallet className="text-emerald-500" />}
                    trend="up"
                />
                <GlassMetric
                    title="Global Margin"
                    value={`${analytics.globalMargin.toFixed(1)}%`}
                    subtext="Profitability"
                    icon={<Activity className={analytics.globalMargin < 20 ? 'text-rose-500' : 'text-indigo-500'} />}
                    trend={analytics.globalMargin < 20 ? 'down' : 'up'}
                />
                <GlassMetric
                    title="Active Load"
                    value={analytics.activeLoad.toString()}
                    subtext="Tasks In Progress"
                    icon={<Zap className="text-amber-500" />}
                />
                <GlassMetric
                    title="Review Queue"
                    value={analytics.reviewQueue.toString()}
                    subtext="Assets Pending"
                    icon={<CheckCircle className="text-blue-500" />}
                />
            </div>

            {/* BUSINESS INTELLIGENCE ROW */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
                <RevenueBreakdown data={analytics.revenueMix} />
                <ClientPipeline data={analytics.clientPipeline} />
            </div>

            {/* MAIN VISUALIZATION GRID */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 h-auto lg:h-[600px]">

                {/* 1. RISK MATRIX (SCATTER) */}
                <RiskMatrix
                    data={analytics.riskMatrix}
                    zoomed={zoomedTile === 'risk'}
                    onToggleZoom={() => setZoomedTile(zoomedTile === 'risk' ? null : 'risk')}
                    onChartClick={handleChartClick}
                />

                {/* 2. ORACLE INSIGHTS & TEAM VELOCITY */}
                <div className="col-span-1 flex flex-col gap-8 h-full">
                    <OracleWidget
                        insight={insight}
                        isAnalyzing={isAnalyzing}
                        onRunPrediction={runPrediction}
                        onExecuteAction={handleExecuteRecommendation}
                    />
                    <TeamVelocity data={analytics.teamStats} />
                </div>
            </div>

            {/* FINANCIAL BREAKDOWN */}
            <BudgetTrend data={analytics.financialTrend} />

            {/* {showGemAI && <GemPhotoAI onClose={() => setShowGemAI(false)} />} */}
            {/* {selectedProject && (
                <ProjectQuickView
                    project={selectedProject}
                    onClose={() => setSelectedProject(null)}
                    onAction={handleQuickAction}
                />
            )} */}
            {zoomedTile && <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-40 transition-opacity" onClick={() => setZoomedTile(null)} />}
        </div>
    );
};
